modLoader="javafml"
loaderVersion="[38,)"
license="MIT"

[[mods]]
  modId="simpletextoverlay"
  displayName="Simple Text Overlay"
  description="Display extra information on top of your in-game screen."
  version="${file.jarVersion}"
  displayURL="https://github.com/wendall911/SimpleTextOverlay"
  updateJSONURL="https://raw.githubusercontent.com/wendall911/SimpleTextOverlay/1.15.2/files/updates.json"
  authors="wendall911"
  credits="DaftPVF, bspkrs, Lunatrius, ashar42"
  logoFile=""

[[dependencies.simpletextoverlay]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simpletextoverlay]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"
